site_name: BRB Mobilidade Desktop
nav:
  - Home: index.md
  - Apresentações: apresentações/apresentacoes.md
  - Planejamento: planejamento.md
  - Contexto de uso: 
    - Perfis de usuário e personas: usuários/perfilDeUsuarios.md
    - Análise de tarefas: usuários/análise de tarefas.md
  - Análise de requisitos: 
    - Princípios gerais: analisederequisitos/principiosgerais.md
    - Metas de usabilidade: analisederequisitos/metasdeusabilidade.md
    - Guia de estilo: analisederequisitos/guiadeestilo.md
  - Storyboard: analisederequisitos/storyboard.md

theme:
  name: null
  custom_dir: mkdocs-material/material
  language: pt
  palette:
    scheme: default
    primary: indigo
    accent: light blue
  font:
    text: Roboto
  icon: 
    logo: material/library
    repo: fontawesome/brands/github
  favicon: images/brblogo.png
  features:
    - instant
  extra:
    - icon: fontawesome/brands/github
      link: https://interacao-humano-computador.github.io/2020.1-BRBMobilidade/
plugins:
  - search:
      separator: '[\s\-\.]+'
repo_url: https://interacao-humano-computador.github.io/2020.1-BRBMobilidade/
markdown_extensions:
  - toc:
      permalink: false
edit_uri: ""